# infra/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecom-frontend
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      containers:
        - name: ecom-frontend
          image: acrecomt5.azurecr.io/ecom-frontend:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ecom-frontend-svc
spec:
  selector:
    app: ecom-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
