name: Backend CI/CD

on:
  push:
    branches:
      - "main"
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2: Login to Azure using Service Principal JSON Secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to Azure Container Registry
      - name: ACR Login
        uses: azure/docker-login@v2
        with:
          login-server: acrecomt5.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 4: Build and Push Backend Docker Image
      - name: Build & Push Backend Image
        run: |
          cd backend
          docker build -t acrecomt5.azurecr.io/ecom-backend:${{ github.sha }} .
          docker push acrecomt5.azurecr.io/ecom-backend:${{ github.sha }}

      # Step 5: Set AKS context to deploy
      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: rg-ecom-dev-t5
          cluster-name: aks-ecom-dev

      # Step 6: Deploy latest image to AKS
      - name: Deploy to AKS
        run: |
          kubectl set image deployment/ecom-backend ecom-backend=acrecomt5.azurecr.io/ecom-backend:${{ github.sha }}
          kubectl rollout status deployment/ecom-backend
