name: Backend CI/CD

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Debug secret presence
        run: |
          echo "CLIENT ID LENGTH: ${#AZURE_CLIENT_ID}"
          echo "TENANT ID LENGTH: ${#AZURE_TENANT_ID}"
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: ACR Login using Service Principal
        uses: azure/docker-login@v2
        with:
          login-server: acrecomt5.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build & Push Backend Image
        run: |
          cd backend
          docker build -t acrecomt5.azurecr.io/ecom-backend:${{ github.sha }} .
          docker push acrecomt5.azurecr.io/ecom-backend:${{ github.sha }}

      - name: Set AKS Context
        uses: azure/aks-set-context@v4
        with:
          resource-group: rg-ecom-dev-t5
          cluster-name: aks-ecom-dev

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/ecom-backend ecom-backend=acrecomt5.azurecr.io/ecom-backend:${{ github.sha }}
          kubectl rollout status deployment/ecom-backend
